### ISSUE TITLE
Server Test Suite v0.13.0: Questions regarding input validation

### ISSUE THREAD

**Issue by jinlouISC** [inferno-framework/davinci-dtr-test-kit#32]
### Test Suite: Da Vinci DTR Payer Server Test Suite v.0.13.0

**Test Case: 1.02 User Input Validation: Client sends payer server a request for a static form**
I used the example bundle from DTR IG [Artifacts](https://hl7.org/fhir/us/davinci-dtr/STU2/Parameters-QuestionnairePackageInputParamsExample.json.html) but the test marked it as failure because of the following reason: 

> Parameters/QuestionnairePackageInputParamsExample: Parameters.parameter[0].resource/Coverage/CoverageExample/.payor[0]: Unable to find a match for profile #OrgExample among choices: http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-organization, http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient.

In this case, should I add "http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-organization" into Coverage.meta.profile[]?

**Test Case: 1.03 Validate that the static response conforms to the Output Parameters profile**
The Inferno http request contains the following content-type header:

> - content-type: application/fhir+json
> - content-type: application/json

Our test server returns a 415 status, as "application/json" shouldn't be allowed here. I believe it should only have "content-type: application/fhir+json".

**Comment by rpassas** [comment]
Hi,
As for the 1.02 reference issue, the contained organization resource does not contain the [CRD Organization](https://build.fhir.org/ig/HL7/davinci-crd//StructureDefinition-profile-organization.html) required identifier which is likely causing an issue. As for the header, `application/json` was required elsewhere and its inclusion here was an oversight on our part. We will patch this, thanks.

**Comment by jinlouISC** [comment]
Hi @rpassas , I agree that 1.02 failure is caused by bad data. For 1.03, that sounds good. Thank you for taking a look!

**Comment by tstrass** [comment]
Fixed in #37. Thanks for reporting this @jinlouISC.

**Comment by jinlouISC** [comment]
@tstrass Thank you for the update! Is there a tentative date to share for release 0140?

**Comment by tstrass** [comment]
@jinlouISC It will most likely be released later today or Monday. And it will most likely be deployed to inferno-qa.healthit.gov Monday and to inferno.healthit.gov Tuesday

**Comment by jinlouISC** [comment]
@tstrass Perfect, thank you for the heads up!
